.Dd July 24, 2017
.Dt RATIONALIS.CONF 5
.Os
.\" ---------------------------------------------------------------------------
.Sh NAME
.Nm rationalis.conf
.Nd rationalis configuration file
.\" ---------------------------------------------------------------------------
.Sh DESCRIPTION
TODO
.\" ---------------------------------------------------------------------------
.Sh FILES
.Bl -tag -width 34 -compact
.It Pa ~/.config/rationalis/config
TODO
.El
.\" ---------------------------------------------------------------------------
.Sh SEE ALSO
.Xr ledger 1 ,
.Xr rationalis 5 ,
.Xr rationalis.rules 5
.\" ---------------------------------------------------------------------------
.Sh AUTHORS
.Nm
was written by
.An Damir Jelić Aq Mt poljar@termina.org.uk .
