.Dd July 24, 2017
.Dt RATIONALIS.RULES 5
.Os
.Sh NAME
.Nm rationalis.rules
.Nd rationalis configuration file
.Sh SYNOPSIS
.Pa $XDG_CONFIG_HOME/rationalis/config
.Sh DESCRIPTION
TODO
.Sh FILES
.Bl -tag -width 34 -compact
.It Pa $XDG_CONFIG_HOME/rationalis/config
TODO
.El
.Sh SEE ALSO
.Xr ledger 1 ,
.Xr rationalis 5 ,
.Xr rationalis.rules 5
.Sh AUTHORS
.Nm
was written by
.An Damir Jelić Aq Mt poljar@termina.org.uk .
